import { Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { Pressable, StyleSheet, Switch, Text, TextInput, View } from 'react-native';

import { CareButton, Header, Screen } from '@/components/careon/shared';
import { CAREON_COLORS, CAREON_SHADOW } from '@/lib/careon-theme';
import { replaceRoute } from '@/lib/navigation';
import { useWear } from '@/lib/wear-state';
const RADIUS = [100, 150, 300, 500];
export default function SafeZoneScreen() {
 const { safeZone, saveSafeZone } = useWear(); const [enabled,setEnabled]=useState(safeZone.enabled); const [name,setName]=useState(safeZone.name); const [radius,setRadius]=useState(safeZone.radiusMeters);
 const save=()=>{saveSafeZone({...safeZone,enabled,name:name.trim()||'안심 구역',radiusMeters:radius});replaceRoute('/wear');};
 return <Screen scroll backgroundColor={CAREON_COLORS.page} contentStyle={styles.content}><Header onBack={()=>replaceRoute('/wear')} title="안심 구역 설정" /><Text style={styles.description}>워치가 구역 밖에 머무르면 상태 확인을 요청해요.</Text><View style={styles.card}><View style={styles.row}><View><Text style={styles.label}>안심 구역 사용</Text><Text style={styles.hint}>한 명당 한 개의 원형 구역을 설정할 수 있어요</Text></View><Switch value={enabled} onValueChange={setEnabled} trackColor={{false:CAREON_COLORS.line,true:CAREON_COLORS.primary}} /></View></View><View style={styles.card}><Text style={styles.label}>구역 이름</Text><TextInput value={name} onChangeText={setName} placeholder="예: 집" style={styles.input} /><Text style={[styles.label,{marginTop:20}]}>중심 위치</Text><View style={styles.location}><Ionicons color={CAREON_COLORS.primaryDark} name="location" size={20}/><View><Text style={styles.locationTitle}>현재 등록 위치</Text><Text style={styles.hint}>{safeZone.latitude}, {safeZone.longitude}</Text></View></View><Text style={[styles.label,{marginTop:20}]}>반경</Text><View style={styles.choices}>{RADIUS.map(value=><Pressable key={value} onPress={()=>setRadius(value)} style={[styles.choice,radius===value&&styles.choiceActive]}><Text style={[styles.choiceText,radius===value&&styles.choiceTextActive]}>{value}m</Text></Pressable>)}</View></View><CareButton onPress={save}>저장</CareButton></Screen>;
}
const styles=StyleSheet.create({content:{padding:24,paddingTop:20},description:{color:CAREON_COLORS.muted,fontSize:14,fontWeight:'600',lineHeight:21,marginBottom:20},card:{backgroundColor:CAREON_COLORS.background,borderRadius:22,marginBottom:16,padding:18,...CAREON_SHADOW},row:{alignItems:'center',flexDirection:'row',justifyContent:'space-between'},label:{color:CAREON_COLORS.title,fontSize:16,fontWeight:'900'},hint:{color:CAREON_COLORS.muted,fontSize:12,fontWeight:'600',lineHeight:18,marginTop:4},input:{borderBottomColor:CAREON_COLORS.line,borderBottomWidth:1,color:CAREON_COLORS.text,fontSize:16,fontWeight:'700',marginTop:10,paddingVertical:10},location:{alignItems:'center',backgroundColor:'#EEF8F5',borderRadius:15,flexDirection:'row',gap:10,marginTop:10,padding:13},locationTitle:{color:CAREON_COLORS.primaryDark,fontSize:14,fontWeight:'800'},choices:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:12},choice:{borderColor:CAREON_COLORS.line,borderRadius:16,borderWidth:1,paddingHorizontal:14,paddingVertical:9},choiceActive:{backgroundColor:CAREON_COLORS.primary,borderColor:CAREON_COLORS.primary},choiceText:{color:CAREON_COLORS.muted,fontSize:13,fontWeight:'800'},choiceTextActive:{color:'#FFF'}});
